name: Terraform CI

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: name: Terraform CI

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Version
        run: terraform version
        run: echo "GitHub Actions is Working!"
  
